### ISSUE TITLE
Caret position on mouse-select yields to incorrect yanked text

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#1646]
When performing mouse select (drag or double-click), VsVim positions the cursor after the end of the select. This affect copy operations because now they include an extra character. 

For example, given `public IEnumerable<string>`, if you double-click `IEnumerable` - the visual selection contains `IEnumerable`, but the caret is on `<` and yanking after this select operation puts `IEnumerable<` in the register. I expected `IEnumerable` to be in the register because that's what's visually selected.
Same behavior if you mouse-drag to select the word `IEnumerable`.

(VsVim 1.8.0.0 with VS 2013 Update 4)

**Comment by philipmat** [comment]
Fixed in VsVim 2.0.1.0 - the cursor is still in the incorrect position, but the text yanked matches the selection.

**Comment by philipmat** [comment]
No, sorry, I was wrong - still seeing this happening.

**Comment by jaredpar** [comment]
I'm unable to reproduce this bug.  I'm using VsVim 2.0.0.0.  The behavior I see is that double click will select the word and move the caret after the selection (caret is not a part of selection here).  A <kbd>y</kbd> in this case will select only the selected text.  

This bug did exist in the past (see #1465).  That should have been fixed by 1.8.0.0 though.

**Comment by philipmat** [comment]
It still happens, but – ugh – I don't have a reproducible scenario. When it happens though, disabling (Ctrl-F12) and re-enabling VsVim makes it go away. 

I'm going to close this issue and re-open it if I found a way to reproduce it.
